### PR TITLE
javascript-conditionals - Alan Ho

### PR DESCRIPTION
**Pull request by alanho-05**

### CODE REVIEW

**Review by shawnkost — CHANGES_REQUESTED** [review]
Hey Alan! Please include a screenshot of you calling some of the functions in the console please!

**Comment by alanho-05** [comment]
Sorry about that! Here is a screenshot of my console with some function calls.

Screenshot 2023-03-22 at 3 54 07 PM

**Review by shawnkost — CHANGES_REQUESTED** [review]
One small change requested Alan!

**Review by shawnkost — APPROVED** [review]
Ahh my bad Alan! Technically your last answer was correct because you were checking if they were greater than 20. My apologies, I was expecting to see 21 😓

**Pull request merged**
